<?php

namespace PpgwBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{
    public function getGeographicRegionQuery($start, $end)
    {
        //returns a query result
        $qb = $this->createQueryBuilder('c');
        
        return $qb->select('c')
                ->where($qb->expr()->between('c.id', $start, $end))
                ->addOrderBy('c.name', 'ASC');
    }
    public function getGeographicRegion($start, $end)
    {
        //returns an entity
        return $this->getGeographicRegionQuery($start, $end)
            ->getQuery()
            ->getResult();
    }
}
